@startuml
skinparam backgroundColor #fff
skinparam defaultFontColor #37474f
skinparam defaultFontSize 14
skinparam defaultFontName serif
skinparam defaultFontStyle bold
skinparam actorBackgroundColor #fff
skinparam actorBorderColor #000
skinparam boundaryBackgroundColor #fff
skinparam boundaryBorderColor #000
skinparam controlBackgroundColor #fff
skinparam controlBorderColor #000
skinparam entityBackgroundColor #fff
skinparam entityBorderColor #000
skinparam participantBackgroundColor #fff
skinparam participantBorderColor #000
skinparam ArrowColor #000
skinparam sequenceLifeLineBorderColor #000
skinparam sequenceBoxBorderColor #FFF
skinparam ParticipantPadding -80

title Diagramme de séquence : Ajouter publication - scénario nominal

hide footbox


actor Étudiant as student

boundary accueilTemplate
boundary formTemplate
control PublicationComposant
entity PublicationDépôt

student ->  accueilTemplate : cliquez sur Ajouter
create formTemplate
accueilTemplate ->  formTemplate
student ->  formTemplate : cliquez sur publier
formTemplate -> PublicationComposant : soumettre(pub)
PublicationComposant -> PublicationDépôt : insérer(pub)
PublicationDépôt --> PublicationComposant : ok
PublicationComposant --> formTemplate: ok
formTemplate --> student :Publié avec succès

@enduml