@startuml
skinparam backgroundColor #fff
skinparam defaultFontColor #37474f
skinparam defaultFontSize 14
skinparam defaultFontName serif
skinparam defaultFontStyle bold
skinparam actorBackgroundColor #fff
skinparam actorBorderColor #000
skinparam boundaryBackgroundColor #fff
skinparam boundaryBorderColor #000
skinparam controlBackgroundColor #fff
skinparam controlBorderColor #000
skinparam entityBackgroundColor #fff
skinparam entityBorderColor #000
skinparam participantBackgroundColor #fff
skinparam participantBorderColor #000
skinparam ArrowColor #000
skinparam sequenceLifeLineBorderColor #000
skinparam sequenceBoxBorderColor #FFF
skinparam ParticipantPadding -80

title Diagramme de séquence : Créer un nouveau compte - scénario nominal

hide footbox


actor Étudiant as student

boundary InscrireTemplate
boundary EmailVeriTemplate
control InscrireComposant
entity UtilisateursDépôt
participant GestionnaireEmail

student ->  InscrireTemplate : cliquez sur\n s'inscrire
InscrireTemplate -> InscrireComposant : soumettre(user)
InscrireComposant -> UtilisateursDépôt : insérer(user)
UtilisateursDépôt -> GestionnaireEmail: envoyerEmail()
GestionnaireEmail ->]: envoyer()
GestionnaireEmail --> UtilisateursDépôt : ok
UtilisateursDépôt --> InscrireComposant :ok
InscrireComposant--> InscrireTemplate :Nous avons envoyé\nun lien vers votre email
destroy InscrireTemplate

create EmailVeriTemplate
student -> EmailVeriTemplate:cliquez sur le lien\n qui a été envoyé

@enduml