@startuml
top to bottom direction
skinparam backgroundColor #fff
skinparam defaultFontColor #37474f
skinparam defaultFontSize 16
skinparam defaultFontName serif
skinparam defaultFontStyle bold
skinparam usecaseBackgroundColor #fff
skinparam usecaseBorderColor #000
skinparam usecaseArrowColor #000
skinparam usecaseActorBorderColor black




rectangle "Raffinement du cas d’utiilisation\n Interagir avec une publication"{

usecase  reportViolations as "Report violations"
usecase  answerQuestion as "Répondez aux questions"
usecase  comment as "Commenter sur \nune publication"
usecase  evaluate as "Évaluer une réponse"
usecase  interact as "Interagir avec\n une publication"




interact <|-- answerQuestion
interact <|-- comment
interact <|-- evaluate
interact <|- reportViolations

}
@enduml