@startuml
skinparam backgroundColor #fff
skinparam defaultFontColor #37474f
skinparam defaultFontSize 18
skinparam defaultFontName serif
skinparam defaultFontStyle normal
skinparam classAttributeIconSize 0
skinparam classBackgroundColor #fff
skinparam classBorderColor #000
skinparam classArrowColor #000

hide class circle

class "Spécialité" as specialty{
-id : long
-abb : String
-nom : String
}
class "Module" as module{
-id : long
-abb : String
-nom : String
-semestre : int
}

class  "Utilisateur"  as user{
-id : long
-prenom : String
-ImageProfil : String
-nom : String
-email : String
-nomUtilisateur : String
-passe : String
-annee : int
}



class "Contribution" as contribution {
-id : long
-description : String
-date : Date
}

class "Publication" as post{
-titre :string
}

class "Commentaires" as comments

class "Reponse" as response{
-points : int
-approuver: boolean
}

class "Attachement" as media{
id : long
link : string
}

specialty  *-- "1.*" module : "est enseigné dans            "
user  *-- "0.*" contribution : "  est contribué par   "
user  "1.*" --o "1" specialty : "Appartient à"
contribution  "0.*" --o "1" module : "Lié à     "


contribution "1.*" o-- "0.*" media : "Attaché"
contribution <|-- post
contribution <|-- comments
contribution <|-- response
post "1" -* "0.*" comments : \tcontient\t
@enduml