@startuml
left to right direction
skinparam backgroundColor #fff
skinparam defaultFontColor #37474f
skinparam defaultFontSize 16
skinparam defaultFontName serif
skinparam defaultFontStyle bold
skinparam usecaseBackgroundColor #fff
skinparam usecaseBorderColor #000
skinparam usecaseArrowColor #000
skinparam usecaseActorBorderColor black
skinparam actorBackgroundColor #fff
skinparam actorBorderColor #000



actor Administrateur as admin
actor Étudiant as student

rectangle "Diagramme de cas d'utilisation \ndu système d'apprentissage social"{

usecase shareContent as "Partager les publications"
usecase interact as "Interagir avec\n une publication"
usecase downloadContent as "Télécharger les pièces\n jointes a une publications"

usecase login as "S'Authentifier
                 --
                 (Créer un  nouveau \n compte)
                 Pas déjà enregistré
                 --
                 (Récupérer le mot de passe)
                 Il a oublié le mot de pass"
usecase  register as "Créer un  nouveau \n compte"
usecase  recover  as "Récupérer le mot \nde passe"
usecase  communicate  as "Discuter \navec les autres"
usecase  defineMSY as "Définir \ndes modules,\n des spécialités \npar années"
usecase  deleteViolations as "Supprimer les violations"
usecase  editProfil as "Mettre à jour le profil"

student <|- admin

login   <. recover   : extends
register  .> login  : extends

shareContent ..> login : include
interact ..> login : include
communicate ..> login : include
downloadContent ..> login : include
defineMSY ..> login : include
deleteViolations ..> login : include
editProfil ..> login : include


admin -- defineMSY
admin -- deleteViolations
student -- shareContent
student -- interact
student -- communicate
student -- downloadContent
student -- editProfil
}
@enduml